### ISSUE TITLE
Include Yosys in VtR test infrastructure

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/vtr-verilog-to-routing#110]
As SymbiFlow heavily depends on Yosys it would be useful to integrate it in the VtR testing infrastructure to let it possible having SymbiFlow tests being run directly in VtR.

### Todo

* [ ] Check how the testing infrastructure is built to easily inject Yosys in the flow
* [ ] Try to use Yosys in the flow with a simple test
* [ ] Make a mergable patch that includes Yosys in VtR
